// generated by mojulo export-unity — do not hand-edit; re-mint from recipe/
/// <summary>
/// Mojulo pack importer (editor-only). World pack: builds one scene from
/// MojuloPack/score.json + model.glb. Game pack (MojuloPack/game.json
/// present): builds one scene per level from levels/&lt;ref&gt;/ plus the menu
/// scene, and writes them all into the build settings scene list (menu
/// first). Static geometry (ground, colliders, spawn marker, editor camera,
/// light) is baked into the saved .unity scenes; the dynamic half (walker,
/// mechanics, HUD) is performed at play time by Runtime/MojuloLevel.cs.
/// Idempotent: re-running against a re-exported pack rebuilds in place.
/// Entry points: menu "Tools > Mojulo > Import Pack"; batchmode
/// Mojulo.Import.Run and Mojulo.Import.Verify (writes mojulo-gate.json).
/// </summary>
using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

namespace Mojulo
{
    public static class Import
    {
        const string PackRoot = "Assets/MojuloPack";
        static string ScenesDir => PackRoot + "/Scenes";
        static Vector3 P(float[] v) { return MojuloLevel.P(v); }

        [Serializable] class GameLevel { public string title; public string @ref; }
        [Serializable] class GameManifest { public string title; public GameLevel[] levels; }

        [MenuItem("Tools/Mojulo/Import Pack")]
        public static void RunMenu() { Debug.Log("[mojulo] " + Build()); }

        /// <summary>Batchmode entry: -executeMethod Mojulo.Import.Run</summary>
        public static void Run()
        {
            try { Debug.Log("[mojulo] " + Build()); if (Application.isBatchMode) EditorApplication.Exit(0); }
            catch (Exception e) { Debug.LogError("[mojulo] import FAILED: " + e.Message); if (Application.isBatchMode) EditorApplication.Exit(1); else throw; }
        }

        static bool IsGame() { return File.Exists(PackRoot + "/game.json"); }

        static GameManifest ReadGame()
        {
            return JsonUtility.FromJson<GameManifest>(File.ReadAllText(PackRoot + "/game.json"));
        }

        static MojuloLevel.Score ReadScore(string resBase)
        {
            var p = resBase + "score.json";
            if (!File.Exists(p)) throw new Exception("score.json not found at " + p + " — copy the pack to " + PackRoot + " (IMPORT-GUIDE.md T004)");
            return JsonUtility.FromJson<MojuloLevel.Score>(File.ReadAllText(p));
        }

        static string Build()
        {
            Directory.CreateDirectory(ScenesDir);
            var scenes = new List<string>();
            string report;
            if (IsGame())
            {
                var game = ReadGame();
                var menuPath = BuildMenuScene(game);
                scenes.Add(menuPath);
                var n = 0;
                foreach (var lv in game.levels)
                {
                    scenes.Add(BuildLevelScene(PackRoot + "/levels/" + lv.@ref + "/", lv.@ref));
                    n++;
                }
                report = "imported game '" + game.title + "' -> menu + " + n + " level scene(s) in " + ScenesDir;
            }
            else
            {
                var scenePath = BuildLevelScene(PackRoot + "/", "mojulo-level");
                scenes.Add(scenePath);
                report = "imported '" + ReadScore(PackRoot + "/").title + "' -> " + scenePath;
            }
            var list = new List<EditorBuildSettingsScene>();
            foreach (var s in scenes) list.Add(new EditorBuildSettingsScene(s, true));
            EditorBuildSettings.scenes = list.ToArray();
            AssetDatabase.Refresh();
            return report;
        }

        static string BuildLevelScene(string resBase, string sceneName)
        {
            var score = ReadScore(resBase);
            var glbPath = resBase + "model.glb";
            var prefab = AssetDatabase.LoadAssetAtPath<GameObject>(glbPath);
            if (prefab == null)
                throw new Exception(glbPath + " produced no prefab — is com.unity.cloud.gltfast installed? (IMPORT-GUIDE.md T003)");

            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var world = (GameObject)PrefabUtility.InstantiatePrefab(prefab);
            world.name = "World";

            // Hide the player-seat body: the operator IS the walker. GLB entity
            // wrappers are named by FIGURE (the id rides glTF extras, which
            // glTFast does not surface as a node name).
            if (!string.IsNullOrEmpty(score.player))
            {
                var seat = FindEntityNode(world.transform, score.entities, score.player);
                if (seat != null) seat.gameObject.SetActive(false);
            }

            // Implicit ground plane at mojulo z = ground: obstacle colliders
            // are hulls only — without this the player falls forever.
            var bounds = new Bounds(P(score.spawn ?? new float[] { 0f, 0f, 0f }), Vector3.one);
            if (score.colliders != null)
                foreach (var b in score.colliders) bounds.Encapsulate(new Bounds(AabbCenter(b), AabbSize(b)));
            var ground = new GameObject("MojuloGround");
            var gc = ground.AddComponent<BoxCollider>();
            ground.transform.position = new Vector3(bounds.center.x, score.ground - 0.5f, bounds.center.z);
            gc.size = new Vector3(bounds.size.x + 400f, 1f, bounds.size.z + 400f);

            var colliderRoot = new GameObject("MojuloColliders");
            if (score.colliders != null)
                for (int i = 0; i < score.colliders.Length; i++)
                {
                    var go = new GameObject("MojuloCollider_" + i);
                    go.transform.SetParent(colliderRoot.transform, false);
                    go.transform.position = AabbCenter(score.colliders[i]);
                    go.AddComponent<BoxCollider>().size = AabbSize(score.colliders[i]);
                }

            var spawn = new GameObject("MojuloSpawn");
            spawn.transform.position = P(score.spawn ?? new float[] { 0f, 0f, 0f });

            // Editor-view camera; MojuloLevel disables it when the walker spawns.
            var camGo = new GameObject("MojuloCamera");
            camGo.AddComponent<Camera>();
            camGo.AddComponent<AudioListener>();
            camGo.transform.position = spawn.transform.position + Vector3.up * (score.eye > 0f ? score.eye : 1.7f);

            var lightGo = new GameObject("MojuloLight");
            var light = lightGo.AddComponent<Light>();
            light.type = LightType.Directional;
            lightGo.transform.rotation = Quaternion.Euler(50f, -30f, 0f);

            // The kernel seat: score + music wired for the runtime half.
            var kernel = new GameObject("MojuloKernel");
            var level = kernel.AddComponent<MojuloLevel>();
            level.scoreJson = AssetDatabase.LoadAssetAtPath<TextAsset>(resBase + "score.json");
            // Y-L1: this level's clips as scene references, scoped to ITS OWN
            // GLB's sub-assets (never AssetDatabase.FindAssets — pack-wide,
            // last level wins). At play time the clips are not in AssetDatabase.
            foreach (var a in AssetDatabase.LoadAllAssetsAtPath(glbPath))
                if (a is AnimationClip ac) level.clips.Add(ac);
            if (!string.IsNullOrEmpty(score.soundtrack))
                level.music = AssetDatabase.LoadAssetAtPath<AudioClip>(PackRoot + "/audio/" + score.soundtrack + ".wav");

            var scenePath = ScenesDir + "/" + sceneName + ".unity";
            if (!EditorSceneManager.SaveScene(scene, scenePath)) throw new Exception("SaveScene failed: " + scenePath);
            Debug.Log("[mojulo] level '" + score.title + "' -> " + scenePath + " (" + (score.colliders != null ? score.colliders.Length : 0) + " colliders)");
            return scenePath;
        }

        static string BuildMenuScene(GameManifest game)
        {
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
            var camGo = new GameObject("MojuloCamera");
            var cam = camGo.AddComponent<Camera>();
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = new Color(0.09f, 0.1f, 0.13f);
            camGo.AddComponent<AudioListener>();
            var menuGo = new GameObject("MojuloMenu");
            var menu = menuGo.AddComponent<MojuloMenu>();
            menu.gameJson = AssetDatabase.LoadAssetAtPath<TextAsset>(PackRoot + "/game.json");
            var menuMusic = AssetDatabase.LoadAssetAtPath<AudioClip>(PackRoot + "/audio/menu.wav");
            if (menuMusic != null) menu.music = menuMusic;
            var scenePath = ScenesDir + "/" + MojuloGame.MenuScene + ".unity";
            if (!EditorSceneManager.SaveScene(scene, scenePath)) throw new Exception("SaveScene failed: " + scenePath);
            return scenePath;
        }

        static Vector3 AabbCenter(MojuloLevel.Aabb b)
        {
            return P(new[] { (b.min[0] + b.max[0]) * 0.5f, (b.min[1] + b.max[1]) * 0.5f, (b.min[2] + b.max[2]) * 0.5f });
        }
        static Vector3 AabbSize(MojuloLevel.Aabb b)
        {
            return new Vector3(b.max[0] - b.min[0], b.max[2] - b.min[2], b.max[1] - b.min[1]);
        }

        static Transform FindDeep(Transform root, string name)
        {
            if (root.name == name) return root;
            for (int i = 0; i < root.childCount; i++)
            {
                var hit = FindDeep(root.GetChild(i), name);
                if (hit != null) return hit;
            }
            return null;
        }

        static Transform FindEntityNode(Transform world, MojuloLevel.Entity[] entities, string id)
        {
            return MojuloLevel.FindEntityNode(world, entities, id);
        }

        /// <summary>Samples the clip on the world root at length/2 and counts the
        /// transforms under 'root' that moved. The subtree is activated for the sample
        /// (the player seat is saved inactive) and restored after.</summary>
        static int MovedUnder(GameObject world, Transform root, AnimationClip clip)
        {
            var wasActive = root.gameObject.activeSelf;
            root.gameObject.SetActive(true);
            var beforePos = new Dictionary<Transform, Vector3>();
            var beforeRot = new Dictionary<Transform, Quaternion>();
            foreach (var t in root.GetComponentsInChildren<Transform>(true))
            {
                beforePos[t] = t.localPosition;
                beforeRot[t] = t.localRotation;
            }
            clip.SampleAnimation(world, clip.length * 0.5f);
            int moved = 0;
            foreach (var kv in beforePos)
                if (kv.Key != null && ((kv.Key.localPosition - kv.Value).magnitude > 1e-4f
                    || Quaternion.Angle(kv.Key.localRotation, beforeRot[kv.Key]) > 0.01f)) moved++;
            foreach (var kv in beforePos) if (kv.Key != null) { kv.Key.localPosition = kv.Value; kv.Key.localRotation = beforeRot[kv.Key]; }
            root.gameObject.SetActive(wasActive);
            return moved;
        }

        /// <summary>Standalone player build: -executeMethod Mojulo.Import.BuildPlayer.
        /// Builds the scene list the importer wrote (menu first for games) into
        /// build/mojulo.app (macOS) / build/mojulo.exe (Windows) for the host
        /// platform. Exit 0 iff the build report says Succeeded.</summary>
        public static void BuildPlayer()
        {
            try
            {
                var scenes = new List<string>();
                foreach (var s in EditorBuildSettings.scenes) if (s.enabled) scenes.Add(s.path);
                if (scenes.Count == 0) throw new Exception("no scenes in build settings — run Mojulo.Import.Run first");
                var target = EditorUserBuildSettings.activeBuildTarget;
                var path = "build/mojulo";
                if (target == BuildTarget.StandaloneOSX) path += ".app";
                else if (target == BuildTarget.StandaloneWindows64 || target == BuildTarget.StandaloneWindows) path += ".exe";
                var report = BuildPipeline.BuildPlayer(scenes.ToArray(), path, target, BuildOptions.None);
                var ok = report.summary.result == UnityEditor.Build.Reporting.BuildResult.Succeeded;
                Debug.Log("[mojulo] player build " + (ok ? "OK" : "FAILED") + " -> " + path
                    + " (" + scenes.Count + " scenes, " + report.summary.totalErrors + " errors)");
                if (Application.isBatchMode) EditorApplication.Exit(ok ? 0 : 1);
                else if (!ok) throw new Exception("build failed — see console");
            }
            catch (Exception e)
            {
                Debug.LogError("[mojulo] player build FAILED: " + e.Message);
                if (Application.isBatchMode) EditorApplication.Exit(1); else throw;
            }
        }

        /// <summary>Machine-gate assertions: -executeMethod Mojulo.Import.Verify.
        /// Writes mojulo-gate.json at the project root; exit 0 iff all pass.</summary>
        public static void Verify()
        {
            var checks = new List<string>();
            var failures = new List<string>();
            void Check(string label, bool ok, string detail)
            {
                checks.Add((ok ? "PASS " : "FAIL ") + label + (detail != null ? " — " + detail : ""));
                if (!ok) failures.Add(label);
            }
            try
            {
                var refs = new List<(string resBase, string sceneName)>();
                if (IsGame())
                {
                    var game = ReadGame();
                    var menuPath = ScenesDir + "/" + MojuloGame.MenuScene + ".unity";
                    Check("menu_scene", File.Exists(menuPath), menuPath);
                    foreach (var lv in game.levels) refs.Add((PackRoot + "/levels/" + lv.@ref + "/", lv.@ref));
                    var inBuild = new HashSet<string>();
                    foreach (var s in EditorBuildSettings.scenes) inBuild.Add(s.path);
                    Check("build_settings", inBuild.Contains(menuPath) && refs.TrueForAll(r => inBuild.Contains(ScenesDir + "/" + r.sceneName + ".unity")), inBuild.Count + " scenes listed");
                }
                else refs.Add((PackRoot + "/", "mojulo-level"));

                bool landmarked = false;
                foreach (var (resBase, sceneName) in refs)
                {
                    var score = ReadScore(resBase);
                    var scenePath = ScenesDir + "/" + sceneName + ".unity";
                    Check(sceneName + ":scene_exists", File.Exists(scenePath), scenePath);
                    if (!File.Exists(scenePath)) continue;
                    EditorSceneManager.OpenScene(scenePath, OpenSceneMode.Single);
                    var world = GameObject.Find("World");
                    Check(sceneName + ":world_instance", world != null, null);
                    var colliderRoot = GameObject.Find("MojuloColliders");
                    int n = colliderRoot != null ? colliderRoot.transform.childCount : -1;
                    Check(sceneName + ":collider_count", n == (score.colliders != null ? score.colliders.Length : 0), n + " vs " + (score.colliders != null ? score.colliders.Length : 0));
                    var spawn = GameObject.Find("MojuloSpawn");
                    bool spawnOk = spawn != null && (spawn.transform.position - P(score.spawn ?? new float[] { 0f, 0f, 0f })).magnitude < 0.01f;
                    Check(sceneName + ":spawn_marker", spawnOk, spawn != null ? spawn.transform.position.ToString("F2") : "missing");
                    Check(sceneName + ":ground_plane", GameObject.Find("MojuloGround") != null, null);
                    var kernel = GameObject.Find("MojuloKernel");
                    var levelComp = kernel != null ? kernel.GetComponent<MojuloLevel>() : null;
                    Check(sceneName + ":kernel_wired", levelComp != null && levelComp.scoreJson != null, null);

                    // Frame-mapping landmark (pinned Y0): an entity node that
                    // survives in the GLB must sit at P(translation).
                    if (!landmarked && world != null && score.entities != null)
                        foreach (var e in score.entities)
                        {
                            var node = FindEntityNode(world.transform, score.entities, e.id);
                            if (node == null || e.translation == null) continue;
                            var want = P(e.translation);
                            var d = (node.position - want).magnitude;
                            Check("frame_landmark:" + e.id, d < 0.5f, node.position.ToString("F2") + " vs " + want.ToString("F2"));
                            landmarked = true;
                            break;
                        }

                    // Rig clips (Y2, upgraded by walking-suit-backport Y-G):
                    // every clip named by entities[].locomotion must exist
                    // among THIS level's model.glb sub-assets AND bind —
                    // sampling it at length/2 must move at least one transform
                    // UNDER THE FIGURE'S WRAPPER (glTFast rebinds clips by node
                    // path; a mismatch animates nothing, silently). Scores with
                    // no locomotion rows keep the Y2 probe: the first clip
                    // moves something, anywhere. Runs LAST: sampling poses the
                    // open scene (the seat is re-activated to sample, unsaved).
                    if (world != null)
                    {
                        var clips = new Dictionary<string, AnimationClip>();
                        foreach (var a in AssetDatabase.LoadAllAssetsAtPath(resBase + "model.glb"))
                            if (a is AnimationClip ac && !clips.ContainsKey(ac.name)) clips[ac.name] = ac;
                        var rows = new List<(string figure, string clip)>();
                        if (score.entities != null)
                            foreach (var e in score.entities)
                                if (e.locomotion != null && !string.IsNullOrEmpty(e.figure))
                                    foreach (var name in new[] { e.locomotion.idle, e.locomotion.walk, e.locomotion.boost })
                                        if (!string.IsNullOrEmpty(name) && !rows.Contains((e.figure, name))) rows.Add((e.figure, name));
                        if (rows.Count > 0)
                        {
                            int bound = 0; var bad = new List<string>();
                            foreach (var (figure, name) in rows)
                            {
                                AnimationClip clip;
                                if (!clips.TryGetValue(name, out clip)) { bad.Add(name + " (no clip)"); continue; }
                                var wrapper = FindDeep(world.transform, figure);
                                if (wrapper == null) { bad.Add(name + " (no wrapper '" + figure + "')"); continue; }
                                int moved = MovedUnder(world, wrapper, clip);
                                if (moved > 0) bound++; else bad.Add(name + " (moves nothing under '" + figure + "')");
                            }
                            var first = clips.Count > 0 ? new List<AnimationClip>(clips.Values)[0] : null;
                            var flavour = first == null ? "" : (first.legacy ? "; legacy clips (kernel loops them per AnimationState)" : "; mecanim clips" + (first.isLooping ? ", looping" : ", NOT looping — loopTime unset"));
                            Check(sceneName + ":clips_bound", bad.Count == 0, bound + " of " + rows.Count + " locomotion clips bind" + flavour + (bad.Count > 0 ? " — " + string.Join(", ", bad) : ""));
                        }
                        else if (clips.Count > 0)
                        {
                            var first = new List<AnimationClip>(clips.Values)[0];
                            int moved = MovedUnder(world, world.transform, first);
                            Check(sceneName + ":clips_bound", moved > 0, clips.Count + " clips; '" + first.name + "' moved " + moved + " transforms");
                        }
                    }
                }
            }
            catch (Exception e)
            {
                Check("verify_ran", false, e.Message);
            }
            var ok = failures.Count == 0;
            var json = "{\"ok\": " + (ok ? "true" : "false") + ", \"checks\": [\"" + string.Join("\", \"", checks) + "\"]}";
            File.WriteAllText("mojulo-gate.json", json);
            Debug.Log("[mojulo] gate " + (ok ? "PASS" : "FAIL") + " (" + checks.Count + " checks)");
            if (Application.isBatchMode) EditorApplication.Exit(ok ? 0 : 1);
        }
    }
}
