// generated by mojulo export-unity — do not hand-edit; re-mint from recipe/
/// <summary>
/// mojulo-unity kernel — the game shell, the C# mirror of the Godot kernel's
/// game.gd autoload. Level flow (menu <-> levels via scene names in the build
/// settings list, written by the importer) and completion progression,
/// persisted in PlayerPrefs under "mojulo.completed". Store slices beyond
/// completion do not travel (see the pack README ledger).
/// </summary>
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Mojulo
{
    public static class MojuloGame
    {
        public const string MenuScene = "mojulo-menu";
        const string SaveKey = "mojulo.completed";
        public static string current;

        public static bool HasMenu() { return Application.CanStreamedLevelBeLoaded(MenuScene); }

        public static HashSet<string> Completed()
        {
            var set = new HashSet<string>();
            foreach (var r in PlayerPrefs.GetString(SaveKey, "").Split('|'))
                if (r.Length > 0) set.Add(r);
            return set;
        }

        public static void StartLevel(string levelRef)
        {
            current = levelRef;
            SceneManager.LoadScene(levelRef);
        }

        public static void LevelComplete(MojuloLevel level)
        {
            if (!string.IsNullOrEmpty(current))
            {
                var done = Completed();
                done.Add(current);
                PlayerPrefs.SetString(SaveKey, string.Join("|", done));
                PlayerPrefs.Save();
            }
            ToMenuBridge.Arm(level, 1.5f);   // the bridge hosts the delayed Go; MojuloLevel has no such method
        }

        public static void LevelFailed(MojuloLevel level) { ToMenuBridge.Arm(level, 1.5f); }

        public static void ToMenu()
        {
            current = null;
            SceneManager.LoadScene(MenuScene);
        }
    }

    /// <summary>Tiny helper: waits out the banner, then returns to the menu
    /// (static classes cannot Invoke; the level MonoBehaviour hosts it).</summary>
    public class ToMenuBridge : MonoBehaviour
    {
        public static void Arm(MojuloLevel level, float delay)
        {
            if (!MojuloGame.HasMenu()) return;
            var bridge = level.gameObject.AddComponent<ToMenuBridge>();
            bridge.Invoke(nameof(Go), delay);
        }
        public void Go() { MojuloGame.ToMenu(); }
    }
}
