// generated by mojulo export-unity — do not hand-edit; re-mint from recipe/
/// <summary>
/// mojulo-unity kernel — the first-person walker. Built by MojuloLevel from
/// the score's eye height (1 mojulo unit = 1 meter at eye 1.7). WASD/arrows +
/// mouse look, Space jumps, Esc frees the mouse (click to recapture).
/// Falling past killY respawns at the spawn point.
/// </summary>
using UnityEngine;

namespace Mojulo
{
    public class MojuloWalker : MonoBehaviour
    {
        public float eye = 1.7f;
        public float speed = 6f;
        public float jump = 4.5f;
        public float gravity = 9.8f;
        public float killY = -100f;
        public Vector3 spawnPos;

        [HideInInspector] public Camera head;
        [HideInInspector] public Transform pitchNode; // Head itself (first person) or the boom pivot (suit)
        CharacterController cc;
        float pitch;
        float fallSpeed;

        /// <summary>Last frame's CharacterController velocity (m/s, world).</summary>
        public Vector3 Velocity { get { return cc != null ? cc.velocity : Vector3.zero; } }

        public void Build(float eyeHeight, float eyeScale)
        {
            eye = eyeHeight;
            cc = gameObject.AddComponent<CharacterController>();
            cc.radius = Mathf.Max(0.3f * eyeScale, 0.05f);
            cc.height = Mathf.Max(1.8f * eyeScale, 2.2f * cc.radius);
            cc.center = new Vector3(0, cc.height / 2f, 0);
            var headGo = new GameObject("Head");
            headGo.transform.SetParent(transform, false);
            headGo.transform.localPosition = new Vector3(0, eye, 0);
            head = headGo.AddComponent<Camera>();
            head.farClipPlane = 8000f;
            headGo.AddComponent<AudioListener>();
            pitchNode = headGo.transform;
        }

        /// <summary>Third-person boom (walking-suit-backport.md rule 7): the
        /// Head hangs 'distance' behind a pivot at 'pivotHeight' (the suit's
        /// chest line) and mouse pitch orbits the pivot. Frames the SUIT, not
        /// the pilot eye — the first shot in Unreal was from inside the hull.</summary>
        public void SetCameraRig(float distance, float pivotHeight)
        {
            if (head == null) return;
            var pivot = new GameObject("Pivot");
            pivot.transform.SetParent(transform, false);
            pivot.transform.localPosition = new Vector3(0, pivotHeight, 0);
            head.transform.SetParent(pivot.transform, false);
            head.transform.localPosition = new Vector3(0, 0, -distance);
            head.transform.localRotation = Quaternion.identity;
            pitchNode = pivot.transform;
        }

        void Start() { Cursor.lockState = CursorLockMode.Locked; }

        void Update()
        {
            if (Input.GetKeyDown(KeyCode.Escape)) Cursor.lockState = CursorLockMode.None;
            else if (Input.GetMouseButtonDown(0)) Cursor.lockState = CursorLockMode.Locked;
            if (Cursor.lockState == CursorLockMode.Locked)
            {
                transform.Rotate(0, Input.GetAxis("Mouse X") * 2.2f, 0);
                pitch = Mathf.Clamp(pitch - Input.GetAxis("Mouse Y") * 2.2f, -86f, 86f);
                if (pitchNode != null) pitchNode.localEulerAngles = new Vector3(pitch, 0, 0);
            }

            if (cc == null) return;
            if (cc.isGrounded)
            {
                fallSpeed = -0.5f;
                if (Input.GetKey(KeyCode.Space)) fallSpeed = jump;
            }
            else fallSpeed -= gravity * Time.deltaTime;

            var dir = Vector3.zero;
            if (Input.GetKey(KeyCode.W) || Input.GetKey(KeyCode.UpArrow)) dir += transform.forward;
            if (Input.GetKey(KeyCode.S) || Input.GetKey(KeyCode.DownArrow)) dir -= transform.forward;
            if (Input.GetKey(KeyCode.A) || Input.GetKey(KeyCode.LeftArrow)) dir -= transform.right;
            if (Input.GetKey(KeyCode.D) || Input.GetKey(KeyCode.RightArrow)) dir += transform.right;
            dir = dir.normalized * speed;
            cc.Move((dir + Vector3.up * fallSpeed) * Time.deltaTime);

            if (transform.position.y < killY) Respawn();
        }

        public void Respawn()
        {
            if (cc != null) cc.enabled = false;
            transform.position = spawnPos;
            fallSpeed = 0f;
            if (cc != null) cc.enabled = true;
        }
    }
}
