// generated by mojulo export-unity — do not hand-edit; re-mint from recipe/
/// <summary>
/// mojulo-unity kernel — the menu, the C# mirror of the Godot kernel's
/// menu.gd. Builds the level list from game.json (assigned by the importer);
/// locked entries show their gate state; completion marks ride PlayerPrefs.
/// IMGUI — zero scene wiring, works in any pipeline.
/// </summary>
using System;
using UnityEngine;

namespace Mojulo
{
    public class MojuloMenu : MonoBehaviour
    {
        public TextAsset gameJson;
        public AudioClip music;

        [Serializable] public class Gate { public string completed; }
        [Serializable] public class LevelEntry { public string title; public string @ref; public Gate gate; }
        [Serializable] public class GameManifest { public string title = "mojulo game"; public LevelEntry[] levels; }

        GameManifest game;

        void Start()
        {
            Cursor.lockState = CursorLockMode.None;
            game = gameJson != null ? JsonUtility.FromJson<GameManifest>(gameJson.text) : new GameManifest();
            if (music != null)
            {
                var audio = gameObject.AddComponent<AudioSource>();
                audio.clip = music; audio.loop = true; audio.Play();
            }
        }

        void OnGUI()
        {
            if (game == null) return;
            var done = MojuloGame.Completed();
            var y = Screen.height * 0.22f;
            var heading = new GUIStyle(GUI.skin.label) { fontSize = 40, alignment = TextAnchor.MiddleCenter };
            heading.normal.textColor = Color.white;
            GUI.Label(new Rect(0, y, Screen.width, 60), game.title, heading);
            y += 90;
            if (game.levels == null) return;
            foreach (var lv in game.levels)
            {
                var label = string.IsNullOrEmpty(lv.title) ? lv.@ref : lv.title;
                var gateRef = lv.gate != null ? lv.gate.completed : "";
                var locked = !string.IsNullOrEmpty(gateRef) && !done.Contains(gateRef);
                if (done.Contains(lv.@ref)) label += "  [done]";
                if (locked) label += "  [locked]";
                GUI.enabled = !locked;
                if (GUI.Button(new Rect(Screen.width / 2f - 220, y, 440, 44), label) && !locked)
                    MojuloGame.StartLevel(lv.@ref);
                GUI.enabled = true;
                y += 56;
            }
        }
    }
}
