// generated by mojulo export-unity — do not hand-edit; re-mint from recipe/
/// <summary>
/// mojulo-unity kernel — the level interpreter, the C# mirror of the Godot
/// kernel's level.gd. Reads the engine-agnostic score.json (z-up frame) and
/// performs the dynamic half live: spawns the walker, marks meshless
/// entities and hazards, interprets the declarative mechanics vocabulary
/// (reach-exit / collect / hazard-damage / survive / fail-on-death), draws
/// the IMGUI HUD and banners, loops the music bed, and performs the score's
/// locomotion rows (walking-suit-backport.md): first-claimant figures play
/// their idle, the player's figure follows the walker as a third-person suit
/// (idle/walk swapped by velocity). Static geometry (ground, colliders, spawn
/// marker) is built at import time by Editor/MojuloImport.cs.
/// One score, three instruments: web, Godot, this.
/// </summary>
using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Animations;
using UnityEngine.Playables;

namespace Mojulo
{
    public class MojuloLevel : MonoBehaviour
    {
        public TextAsset scoreJson;
        public AudioClip music;
        /// <summary>This level's clips, captured by the importer from ITS OWN
        /// model.glb sub-assets (Y-L1) — a scene reference, per level by
        /// construction. Never rebuilt from a pack-wide asset search: a game
        /// pack bakes a shared figure into every level's GLB under identical
        /// clip names, and a pack-wide index makes the last level win.</summary>
        public List<AnimationClip> clips = new List<AnimationClip>();

        [Serializable] public class Aabb { public float[] min; public float[] max; }
        // JsonUtility builds a default instance for an absent nested object —
        // "has a row" is Any(), never a null test.
        [Serializable] public class Locomotion
        {
            public string idle; public string walk; public string boost;
            public bool Any() { return !string.IsNullOrEmpty(idle) || !string.IsNullOrEmpty(walk); }
        }
        [Serializable] public class Entity { public string id; public string figure; public float[] translation; public Locomotion locomotion; }
        [Serializable] public class PickupSpec { public string item = "item"; public float[] at; public float radius = 1.4f; }
        [Serializable] public class HazardSpec { public float[] at; public float radius = 1.5f; public float damage = 20f; }
        [Serializable] public class Mechanic
        {
            public string kind;
            public float[] at;
            public float[] half;
            public float radius = 2f;
            public bool planar = true;
            public PickupSpec[] pickups;
            public HazardSpec[] hazards;
            public float seconds = 30f;
            public float startHp = 100f;
        }
        [Serializable] public class Score
        {
            public string title;
            public float[] spawn;
            public float eye = 1.7f;
            public float ground;
            public Aabb[] colliders;
            public Entity[] entities;
            public Mechanic[] mechanics;
            public string player;
            public string soundtrack;
        }

        // The one frame conversion: mojulo z-up right-handed -> Unity y-up
        // left-handed (glTF y-up root rotation composed with glTFast's X
        // negation). Pinned by the machine gate's frame landmark.
        public static Vector3 P(float[] v) { return new Vector3(-v[0], v[2], -v[1]); }

        const float HazardCooldown = 0.8f;

        Score score;
        MojuloWalker walker;
        float eyeScale = 1f;
        string state = "playing"; // playing | complete | failed
        string banner;
        float bannerAt = -1f;

        class Zone { public Vector3 pos; public float[] half; public float radius; public bool planar; }
        class Pickup { public string item; public Vector3 pos; public float radius; public bool taken; public GameObject marker; }
        class Hazard { public Vector3 pos; public float radius; public float damage; public float cool; }

        readonly List<Zone> exits = new List<Zone>();
        readonly List<Pickup> pickups = new List<Pickup>();
        readonly List<Hazard> hazards = new List<Hazard>();
        readonly Dictionary<string, int> bag = new Dictionary<string, int>();
        float surviveLeft = -1f;
        bool failOnDeath;
        float hp = -1f;
        float startHp = 100f;

        // Rig playback (Y-L2). glTFast roots every clip's binding paths at
        // the prefab root (World) and, per its import setting, delivers
        // either LEGACY clips (the shipped-.meta default: an Animation
        // component on World, clips not looping) or MECANIM clips (an
        // Animator on World, loopTime set). The kernel plays both, chosen by
        // the clips' own legacy flag, through one seam: one LAYER per
        // playing clip, layers overriding only the properties they animate,
        // so figures on disjoint node paths never fight.
        IRig rig;
        readonly Dictionary<string, AnimationClip> clipIndex = new Dictionary<string, AnimationClip>();
        // The walking suit (Y-L4): the player's figure wrapper, driven by the walker.
        Transform suit;
        Quaternion suitBaseRot;
        float suitBaseYaw;
        bool suitMoving;
        AnimationClip suitIdle, suitWalk;
        int suitLayer = -1;

        interface IRig
        {
            /// <summary>Play the clip looping on a layer at a weight (0 = parked, phase kept).</summary>
            void Add(AnimationClip clip, int layer, float weight);
            /// <summary>Rule 6: hand the layer from one cycle to the other — never a stop.</summary>
            void Swap(AnimationClip from, AnimationClip to, float fade);
            void Dispose();
        }

        /// <summary>Legacy clips — the Animation component glTFast already put on
        /// World (or a fresh one). AnimationState per clip: layer, loop, weight.</summary>
        class LegacyRig : IRig
        {
            readonly Animation anim;
            public LegacyRig(GameObject world)
            {
                anim = world.GetComponent<Animation>();
                if (anim == null) anim = world.AddComponent<Animation>();
                anim.playAutomatically = false;
                anim.cullingType = AnimationCullingType.AlwaysAnimate;
            }
            public void Add(AnimationClip clip, int layer, float weight)
            {
                if (anim.GetClip(clip.name) == null) anim.AddClip(clip, clip.name);
                var st = anim[clip.name];
                st.layer = layer;
                st.wrapMode = WrapMode.Loop;
                st.weight = weight;
                st.speed = weight > 0f ? 1f : 0f;
                st.enabled = true;
            }
            public void Swap(AnimationClip from, AnimationClip to, float fade)
            {
                anim[from.name].speed = 0f;
                anim[to.name].speed = 1f;
                anim.CrossFade(to.name, fade, PlayMode.StopSameLayer);
            }
            public void Dispose() { }
        }

        /// <summary>Mecanim clips — a Playables graph on World's Animator with an
        /// AnimationLayerMixerPlayable (a plain mixer would fill every
        /// un-animated property with defaults at each input's weight and
        /// over-blend N figures). No AnimatorController involved.</summary>
        class MecanimRig : IRig
        {
            PlayableGraph graph;
            AnimationLayerMixerPlayable layers;
            readonly Dictionary<AnimationClip, int> slot = new Dictionary<AnimationClip, int>();
            readonly Dictionary<AnimationClip, AnimationClipPlayable> playable = new Dictionary<AnimationClip, AnimationClipPlayable>();
            public MecanimRig(GameObject world)
            {
                var animator = world.GetComponent<Animator>();
                if (animator == null) animator = world.AddComponent<Animator>();
                animator.cullingMode = AnimatorCullingMode.AlwaysAnimate;
                graph = PlayableGraph.Create("MojuloRigs");
                graph.SetTimeUpdateMode(DirectorUpdateMode.GameTime);
                layers = AnimationLayerMixerPlayable.Create(graph, 0);
                AnimationPlayableOutput.Create(graph, "MojuloRigs", animator).SetSourcePlayable(layers);
            }
            public void Add(AnimationClip clip, int layer, float weight)
            {
                if (slot.ContainsKey(clip)) return;
                var p = AnimationClipPlayable.Create(graph, clip);
                p.SetApplyFootIK(false);
                var i = layers.GetInputCount();
                layers.SetInputCount(i + 1);
                graph.Connect(p, 0, layers, i);
                layers.SetInputWeight(i, weight);
                if (weight <= 0f) p.Pause();
                slot[clip] = i; playable[clip] = p;
                if (!graph.IsPlaying()) graph.Play();
            }
            public void Swap(AnimationClip from, AnimationClip to, float fade)
            {
                int a, b;
                if (!slot.TryGetValue(from, out a) || !slot.TryGetValue(to, out b)) return;
                playable[from].Pause(); playable[to].Play();
                layers.SetInputWeight(a, 0f); layers.SetInputWeight(b, 1f);
            }
            public void Dispose() { if (graph.IsValid()) graph.Destroy(); }
        }

        void Start()
        {
            if (scoreJson == null) { Debug.LogError("[mojulo] MojuloLevel has no score"); return; }
            score = JsonUtility.FromJson<Score>(scoreJson.text);
            eyeScale = Mathf.Max(0.5f, score.eye / 1.7f);
            SpawnWalker();
            BuildRigs();
            MarkMeshlessEntities();
            BuildMechanics();
            StartMusic();
            var editorCam = GameObject.Find("MojuloCamera");
            if (editorCam != null) editorCam.SetActive(false);
        }

        void SpawnWalker()
        {
            var go = new GameObject("MojuloWalkerRoot");
            walker = go.AddComponent<MojuloWalker>();
            var spawn = P(score.spawn ?? new float[] { 0f, 0f, 2f });
            spawn.y += 0.3f * eyeScale;
            walker.spawnPos = spawn;
            go.transform.position = spawn;
            walker.speed = 6f * eyeScale;
            walker.jump = 4.5f * eyeScale;
            walker.gravity = 9.8f * eyeScale;
            var killY = spawn.y - 300f;
            if (score.colliders != null && score.colliders.Length > 0)
            {
                var minZ = float.MaxValue;
                foreach (var c in score.colliders) if (c.min != null) minZ = Mathf.Min(minZ, c.min[2]);
                killY = minZ - 100f;
            }
            walker.killY = killY;
            walker.Build(score.eye > 0f ? score.eye : 1.7f, eyeScale);
        }

        AnimationClip Clip(string name)
        {
            AnimationClip c;
            return !string.IsNullOrEmpty(name) && clipIndex.TryGetValue(name, out c) ? c : null;
        }

        /// <summary>Entity node in the imported World, FIGURE-first (rule 8):
        /// a baked rig's wrapper is named after the figure key — the placement
        /// of the figure's FIRST claiming entity — and only later claimants
        /// and static bodies get an "entity:&lt;id&gt;" node.</summary>
        public static Transform FindEntityNode(Transform world, Entity[] entities, string id)
        {
            if (entities != null)
                foreach (var e in entities)
                    if (e.id == id && !string.IsNullOrEmpty(e.figure))
                    {
                        var byFigure = FindDeep(world, e.figure);
                        if (byFigure != null) return byFigure;
                    }
            return FindDeep(world, "entity:" + id);
        }

        /// <summary>Y-L2 + Y-L3 + Y-L4: the Playables graph, ambient idles
        /// (one baked body per figure ⇒ first claimant only, the player's
        /// figure pre-claimed), and the walking suit.</summary>
        void BuildRigs()
        {
            if (score.entities == null || clips == null || clips.Count == 0) return;
            var world = GameObject.Find("World");
            if (world == null) return;
            AnimationClip any = null;
            foreach (var c in clips) if (c != null && !clipIndex.ContainsKey(c.name)) { clipIndex[c.name] = c; if (any == null) any = c; }
            if (any == null) return;
            rig = any.legacy ? (IRig)new LegacyRig(world) : new MecanimRig(world);
            Debug.Log("[mojulo] rigs: " + clipIndex.Count + " clips, " + (any.legacy ? "legacy" : "mecanim") + " playback");

            var claimed = new HashSet<string>();
            var layer = 1;
            Entity player = null;
            foreach (var e in score.entities) if (e.id == score.player) { player = e; break; }
            if (player != null && !string.IsNullOrEmpty(player.figure)) claimed.Add(player.figure);
            if (player != null && player.locomotion != null && player.locomotion.Any()) SpawnSuit(world.transform, player);

            foreach (var e in score.entities)
            {
                if (e.locomotion == null || string.IsNullOrEmpty(e.locomotion.idle) || string.IsNullOrEmpty(e.figure)) continue;
                if (!claimed.Add(e.figure)) continue; // one body per figure: first claimant idles
                if (FindDeep(world.transform, e.figure) == null) continue;
                var idle = Clip(e.locomotion.idle);
                if (idle == null) continue;
                rig.Add(idle, layer++, 1f);
            }
        }

        /// <summary>The suit is a cosmetic follower (rule 3): its body never
        /// collides (glTFast adds no colliders — keep the import defaults);
        /// blocking is the score colliders' job. The importer baked the seat
        /// hidden for the first-person double — re-activate it here.</summary>
        void SpawnSuit(Transform world, Entity player)
        {
            var seat = FindEntityNode(world, score.entities, player.id);
            if (seat == null) return;
            seat.gameObject.SetActive(true);
            suit = seat;
            suitBaseRot = seat.rotation;
            suitBaseYaw = walker.transform.eulerAngles.y;
            suitIdle = Clip(player.locomotion.idle);
            suitWalk = Clip(player.locomotion.walk);
            suitLayer = 0; // the suit owns layer 0; ambient idles stack above on disjoint paths
            if (suitIdle != null) rig.Add(suitIdle, suitLayer, 1f);
            if (suitWalk != null) rig.Add(suitWalk, suitLayer, suitIdle == null ? 1f : 0f);

            // Y-L5: frame the SUIT — union renderer bounds over the wrapper's
            // subtree; pivot at the chest line, boom ~2 suit-heights back.
            var h = SuitHeight(seat);
            var eye = score.eye > 0f ? score.eye : 1.7f;
            if (h > 0f) walker.SetCameraRig(Mathf.Max(3.5f * eye, 2f * h), 0.55f * h);
            Debug.Log("[mojulo] suit '" + seat.name + "' follows the walker (height " + h.ToString("F1") + " m)");
        }

        static float SuitHeight(Transform root)
        {
            var any = false; var b = new Bounds();
            foreach (var r in root.GetComponentsInChildren<Renderer>())
            {
                if (!any) { b = r.bounds; any = true; } else b.Encapsulate(r.bounds);
            }
            return any ? b.size.y : 0f;
        }

        // Rule 1: placement = the wrapper's transform. Feet follow the walker
        // origin (the CharacterController is centred at height/2, so its origin
        // IS the feet); yaw is a delta composed ON the imported base rotation —
        // never a raw yaw, which strips the frame correction (suit face-down).
        void LateUpdate()
        {
            if (suit == null || walker == null) return;
            suit.position = walker.transform.position;
            suit.rotation = Quaternion.AngleAxis(walker.transform.eulerAngles.y - suitBaseYaw, Vector3.up) * suitBaseRot;
            if (rig == null || suitWalk == null || suitIdle == null) return;
            var v = walker.Velocity;
            var moving = new Vector2(v.x, v.z).magnitude > 0.6f * eyeScale;
            if (moving == suitMoving) return;
            suitMoving = moving;
            // Rule 6: the parked cycle keeps its phase — a hand-over, never a stop.
            if (moving) rig.Swap(suitIdle, suitWalk, 0.15f);
            else rig.Swap(suitWalk, suitIdle, 0.15f);
        }

        void OnDestroy() { if (rig != null) rig.Dispose(); }

        // Entities that baked no mesh get a gold placeholder marker so
        // gameplay anchors are not invisible (same doctrine as Godot).
        void MarkMeshlessEntities()
        {
            if (score.entities == null) return;
            var world = GameObject.Find("World");
            foreach (var e in score.entities)
            {
                if (e.id == score.player || e.translation == null) continue;
                Transform node = null;
                if (world != null && !string.IsNullOrEmpty(e.figure)) node = FindDeep(world.transform, e.figure);
                if (node != null && node.GetComponentInChildren<Renderer>() != null) continue;
                var size = 0.7f * eyeScale;
                var marker = GameObject.CreatePrimitive(PrimitiveType.Cube);
                marker.name = "MojuloEntityMarker_" + e.id;
                UnityEngine.Object.Destroy(marker.GetComponent<Collider>());
                marker.transform.localScale = new Vector3(size, size, size);
                marker.transform.position = P(e.translation) + Vector3.up * (size / 2f);
                marker.GetComponent<Renderer>().material.color = new Color(0.92f, 0.76f, 0.3f);
            }
        }

        static Transform FindDeep(Transform root, string name)
        {
            if (root.name == name) return root;
            for (int i = 0; i < root.childCount; i++)
            {
                var hit = FindDeep(root.GetChild(i), name);
                if (hit != null) return hit;
            }
            return null;
        }

        void BuildMechanics()
        {
            if (score.mechanics == null) return;
            foreach (var m in score.mechanics)
            {
                switch (m.kind)
                {
                    case "reach-exit":
                        exits.Add(new Zone { pos = P(m.at ?? new float[3]), half = m.half, radius = m.radius, planar = m.planar });
                        break;
                    case "collect":
                        if (m.pickups != null)
                            foreach (var p in m.pickups)
                                pickups.Add(new Pickup { item = p.item, pos = P(p.at ?? new float[3]), radius = p.radius, marker = PickupMarker(P(p.at ?? new float[3])) });
                        break;
                    case "hazard-damage":
                        startHp = m.startHp; hp = startHp;
                        if (m.hazards != null)
                            foreach (var h in m.hazards)
                            {
                                var pos = P(h.at ?? new float[3]);
                                hazards.Add(new Hazard { pos = pos, radius = h.radius, damage = h.damage });
                                HazardMarker(pos, h.radius);
                            }
                        break;
                    case "fail-on-death":
                        failOnDeath = true;
                        if (hp < 0f) { startHp = m.startHp; hp = startHp; }
                        break;
                    case "survive":
                        surviveLeft = m.seconds;
                        break;
                }
            }
        }

        GameObject PickupMarker(Vector3 pos)
        {
            var size = 0.5f * eyeScale;
            var marker = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            marker.name = "MojuloPickup";
            UnityEngine.Object.Destroy(marker.GetComponent<Collider>());
            marker.transform.localScale = new Vector3(size, size, size);
            marker.transform.position = pos + Vector3.up * (0.6f * eyeScale);
            marker.GetComponent<Renderer>().material.color = new Color(0.98f, 0.85f, 0.25f);
            return marker;
        }

        // Hazards export no visual at all (score data, not entities) — a
        // translucent danger sphere keeps the gameplay anchor visible.
        void HazardMarker(Vector3 pos, float radius)
        {
            var marker = GameObject.CreatePrimitive(PrimitiveType.Sphere);
            marker.name = "MojuloHazard";
            UnityEngine.Object.Destroy(marker.GetComponent<Collider>());
            marker.transform.localScale = new Vector3(radius * 2f, radius * 2f, radius * 2f);
            marker.transform.position = pos;
            var mat = marker.GetComponent<Renderer>().material;
            mat.color = new Color(0.95f, 0.25f, 0.2f, 0.35f);
            mat.SetFloat("_Mode", 3f); // legacy Standard transparent hint; harmless elsewhere
            mat.renderQueue = 3000;
        }

        void StartMusic()
        {
            if (music == null) return;
            var audio = gameObject.AddComponent<AudioSource>();
            audio.clip = music; audio.loop = true; audio.playOnAwake = false;
            audio.Play();
        }

        // Distance from a point to the walker's BODY (feet -> head segment),
        // not the feet point — a chest-height hazard must still connect.
        float BodyDistance(Vector3 target)
        {
            var feet = walker.transform.position;
            var y = Mathf.Clamp(target.y, feet.y, feet.y + score.eye);
            return Vector3.Distance(target, new Vector3(feet.x, y, feet.z));
        }

        bool ZoneHit(Zone z, Vector3 pos)
        {
            if (z.half != null && z.half.Length >= 3)
            {
                if (Mathf.Abs(pos.x - z.pos.x) > z.half[0] || Mathf.Abs(pos.z - z.pos.z) > z.half[1]) return false;
                return z.planar || Mathf.Abs(pos.y - z.pos.y) <= z.half[2];
            }
            if (z.planar)
                return new Vector2(pos.x - z.pos.x, pos.z - z.pos.z).magnitude <= z.radius;
            return Vector3.Distance(pos, z.pos) <= z.radius;
        }

        void Update()
        {
            if (state != "playing" || walker == null) return;
            if (Input.GetKeyDown(KeyCode.M) && MojuloGame.HasMenu()) { MojuloGame.ToMenu(); return; }
            var pos = walker.transform.position;
            foreach (var z in exits) if (ZoneHit(z, pos)) { Complete(); return; }
            if (surviveLeft >= 0f)
            {
                surviveLeft = Mathf.Max(0f, surviveLeft - Time.deltaTime);
                if (surviveLeft == 0f) { Complete(); return; }
            }
            foreach (var p in pickups)
                if (!p.taken && BodyDistance(p.pos) <= p.radius + 0.4f * eyeScale)
                {
                    p.taken = true;
                    if (p.marker != null) p.marker.SetActive(false);
                    bag[p.item] = (bag.TryGetValue(p.item, out var n) ? n : 0) + 1;
                    Debug.Log("moj: picked up " + p.item);
                }
            foreach (var h in hazards)
            {
                h.cool = Mathf.Max(0f, h.cool - Time.deltaTime);
                if (h.cool == 0f && BodyDistance(h.pos) <= h.radius + 0.4f * eyeScale)
                {
                    h.cool = HazardCooldown;
                    hp = Mathf.Max(0f, hp - h.damage);
                    Debug.Log("moj: hazard hit, hp " + (int)hp);
                    if (failOnDeath && hp <= 0f) { Fail(); return; }
                }
            }
        }

        void Complete()
        {
            state = "complete";
            banner = "LEVEL COMPLETE";
            bannerAt = Time.time;
            Debug.Log("moj: level complete");
            MojuloGame.LevelComplete(this);
        }

        void Fail()
        {
            state = "failed";
            banner = "FAILED";
            bannerAt = Time.time;
            Debug.Log("moj: level failed");
            if (MojuloGame.HasMenu()) MojuloGame.LevelFailed(this);
            else Invoke(nameof(ResetLevel), 1.5f);
        }

        public void ResetLevel()
        {
            banner = null;
            hp = (hp >= 0f || failOnDeath) ? startHp : -1f;
            bag.Clear();
            foreach (var p in pickups) { p.taken = false; if (p.marker != null) p.marker.SetActive(true); }
            if (score.mechanics != null)
                foreach (var m in score.mechanics)
                    if (m.kind == "survive") surviveLeft = m.seconds;
            walker.Respawn();
            state = "playing";
        }

        void OnGUI()
        {
            var parts = new List<string>();
            if (hp >= 0f) parts.Add("HP " + Mathf.CeilToInt(hp));
            if (surviveLeft >= 0f) parts.Add("SURVIVE " + Mathf.CeilToInt(surviveLeft));
            foreach (var kv in bag) parts.Add(kv.Key.ToUpperInvariant() + " ×" + kv.Value);
            if (parts.Count > 0)
                GUI.Label(new Rect(16, 12, 800, 30), string.Join("   ", parts), HudStyle(20, TextAnchor.UpperLeft));
            if (banner != null)
            {
                var style = HudStyle(48, TextAnchor.MiddleCenter);
                style.normal.textColor = state == "failed" ? new Color(1f, 0.35f, 0.3f) : Color.white;
                GUI.Label(new Rect(0, 0, Screen.width, Screen.height), banner, style);
            }
        }

        static GUIStyle HudStyle(int size, TextAnchor anchor)
        {
            var style = new GUIStyle(GUI.skin.label) { fontSize = size, alignment = anchor };
            style.normal.textColor = Color.white;
            return style;
        }
    }
}
